### ISSUE TITLE
Linter incorrectly shows "Missing `kind` field" and "Missing `apiVersion` field" line numbers for valid multidoc yaml with empty docs.

### ISSUE THREAD

**Issue by austinchambers** [replicatedhq/kots-lint#35]
We've recently switched on the new linter. This has resulted in some situations where previously valid yaml is showing incorrect errors. 

# To Repro: 
1. Create a new application, using the default yamls. 
2. Combine all deployment and service yamls together. Verify no errors. 
3. Append the following to the multidoc yaml: 

```
---
# Random Comment

---
#  Random other Comment
```

3. Try to save the release. 

**Expected:** No errors are returned. Or if an error is returned, it points to the line numbers for the empty file. 
**Actual:** Errors are returned. Error shows a line number for valid yaml, citing that "kind" and "apiVersion" is missing. This is misleading. It could be argued that it's invalid to have an empty file, but given that it was previously passing validating, I'd argue that we should continue to treat it as valid. That is continue to accept empty docs in a multidoc stream.

**Comment by dexhorthy** [comment]
I think the best approach here would probably be to accept empty docs in a multidoc stream @salahalsaleh @austinchambers  -- is that a quick fix?

**Comment by austinchambers** [comment]
@dexhorthy Yep. In fact, that's my recommendation here.

**Comment by salahalsaleh** [comment]
@dexhorthy @austinchambers the issue was that the linter does not handle the _first_ empty doc. it handle other empty docs just fine. A proposed fix is here #36
